apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: YWJjZGVmMTIzNDU2 # abcdef123456
  mysql-user: d3B1c2Vy # wpuser
  mysql-password: YWJjZGVmMTIzNDU2 # abcdef123456

---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  wordpress-db-password: YWJjZGVmMTIzNDU2 # abcdef123456
  wordpress-db-user: d3B1c2Vy # wpuser
  wordpress-db-name: d3BkYg== # exampledb