version: "3"

services:

  # WireGuard VPN service
  wireguard:
    image: linuxserver/wireguard:v1.0.20210914-ls6
    container_name: wireguard
    environment:
      - SERVERPORT=10200
      - PUID=1000
      - PGID=1000 
      - TZ=Europe/Paris
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    networks:
      - wg_net
    ports:
      # Port for WireGuard-UI
      #- "80:5000"
      # Port of the WireGuard VPN server
      - "10200:10200/udp"

  # WireGuard-UI service
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    # Use the network of the 'wireguard' service
    # This enables to show active clients in the status page
    network_mode: service:wireguard
    # La directive network_mode place les deux conteneurs sur le même espace de noms réseau, 
    # leur permettant de partager la même pile réseau, la même adresse IP et les mêmes ports TCP ouverts.
    environment:
      - TZ=Europe/Paris
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=$WGUI_USERNAME
      - WGUI_PASSWORD=$WGUI_PASSWORD
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - ./config:/etc/wireguard
  
  # service reverse proxy
  nginx-rp:
    container_name: nginx-rp
    image: nginx:latest
    networks:
      - wg_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl_certs:/etc/ssl/ssl_certs:ro
    restart: always


networks:
  wg_net:
    name: wg_net