version: '3'

services:
  nc_db:
    image: mariadb:11.3.2
    container_name: nc_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - ./db:/var/lib/mysql
     - ./logs/db_logs:/var/log/mysql
    environment:
     - TZ=Europe/Paris
     - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
     - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
     - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
    networks:
     - nextcloud_backend

  nc_app:
    container_name: nc_app
    image: nextcloud:28.0.4
    restart: always
    volumes:
     - ./data:/var/www/html/data
    #  - ./html:/var/www/html
     - ./config:/var/www/html/config
     - ./custom_apps:/var/www/html/custom_apps
     - ./logs/nc_logs:/var/log/apache2

    environment:
     - TZ=Europe/Paris
     - MYSQL_HOST=nc_db
     - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
     - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
     - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
    networks:
     - nextcloud_backend
    ports:
     - 8000:80 
    depends_on:
     - nc_db

networks:
  nextcloud_backend:
    name: nextcloud_backend